### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [grevelem/TC359Project9EG#1]
Looking good, apart from a few items I'd like you to fix, detailed below. Don't hesitate to let me know if you have any questions or get stuck. I'd be happy to point you in the right direction. :smiley: 
#### Extract the menu of links to [`layouts/application.html.erb`](https://github.com/grevelem/TC359Project9EG/blob/master/app/views/layouts/application.html.erb), since you want it on every page

Since we want to show the links on every page, it's best to list them in our layout file so that we only have to include them _once_. Whenever you find yourself with the same exact code copy and pasted in multiple files, that's generally an indication that something's wrong. This way, whenever we want to add, remove, or change a menu item, we only have to do so once. :smiley: 
#### Remove the `<%= yield %>` lines in [these non-layout files](https://github.com/grevelem/TC359Project9EG/tree/master/app/views/static)

The `<%= yield %>` line is actually only necessary once in the layout file. It's used to tell the layout where we want to put the HTML for specific pages, such as those in the `app/views/static` folder. When used in non-layout files, it actually does nothing, so should be removed.
#### Fix inconsistent indentation, such as [here in `static.scss`](https://github.com/grevelem/TC359Project9EG/blob/master/app/assets/stylesheets/static.scss#L9-L11)

I'm sure this was just an overlooked typo, but let's make sure we indent everything consistently. It's very easy to little mistakes like this to accumulate and then our code can get very messy.

**Comment by grevelem** [comment]
Hey Professor Fritz, I think I've got all of the necessary changes completed. Sorry for the late response, I was out of town in Nashville the entire weekend. Let me know if further changes need to be made. Thanks!

**Comment by chrisvfritz** [comment]
:+1: Looking good!
